# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '14.0'

def common_pods
  use_frameworks!
  pod 'SwiftLint'
end

target 'PhotoLibrary' do
  common_pods
end

target 'PhotoLibraryTests' do
  common_pods
end

target 'PhotoLibraryUITests' do
  common_pods
end
